# Generated by Django 4.2.7 on 2024-04-07 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_order_additional_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='скрыт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='дополнительная плата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='скрыт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Админ'), (2, 'Клиент'), (3, 'Менеджер'), (4, 'Доставщик'), (5, 'Шеф')], default=2, verbose_name='роль'),
        ),
    ]
